name: Create Docker image

on: [push, pull_request]

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm ci --production

      - name: Tests, linting and etc
        run: |
          npm run lint:eslint
          npm test

      - name: Build static
        run: |
          npm run build

      - name: Build the Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker login ghcr.io -u anpleenko -p ${{ secrets.TOKEN }}
          docker build . --file Dockerfile --tag bookmarks
          docker tag bookmarks ghcr.io/7qw/sp.vaeum.com/bookmarks-front:latest
          docker push ghcr.io/7qw/sp.vaeum.com/bookmarks-front:latest

      - name: SSH connect
        uses: garygrossgarten/github-action-ssh@release
        if: github.ref == 'refs/heads/main'
        with:
          command: cd /usr/src/docker && ./up.sh
          host: ${{ secrets.HOST }}
          username: deploy
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
