name: Create Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
       docker login docker.pkg.github.com -u anpleenko -p ${{ secrets.TOKEN }}
       docker build . --file Dockerfile --tag 7qw/sp.vaeum.com:test
       docker tag 7qw/sp.vaeum.com:test 7qw/sp.vaeum.com:latest
       docker push docker.pkg.github.com/7qw/sp.vaeum.com:latest
