name: Create Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
       docker login docker.pkg.github.com -u anpleenko -p ${{ secrets.TOKEN }}
       docker build . --file Dockerfile --tag bookmarks
       docker tag bookmarks docker.pkg.github.com/7qw/sp.vaeum.com/bookmarks:latest
       docker images
       docker push docker.pkg.github.com/7qw/sp.vaeum.com/bookmarks:latest
 
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH connect
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /usr/src/docker && ./up.sh
        host: ${{ secrets.HOST }}
        user: deploy
        key: ${{ secrets.PRIVATE_KEY}}
