name: Create Docker image

on: [push, pull_request]

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
   
    - name: Install dependencies and build
      run: |
       npm ci
       npm run build
       
    - name: Build the Docker image
      if: github.ref == 'refs/heads/master'
      run: |
       docker login docker.pkg.github.com -u anpleenko -p ${{ secrets.TOKEN }}
       docker build . --file Dockerfile --tag bookmarks
       docker tag bookmarks docker.pkg.github.com/7qw/bookmarks/bookmarks:latest
       docker push docker.pkg.github.com/7qw/bookmarks/bookmarks:latest
  
    - name: SSH connect
      uses: garygrossgarten/github-action-ssh@release
      if: github.ref == 'refs/heads/master'
      with:
        command: cd /usr/src/docker && ./up.sh
        host: ${{ secrets.HOST }}
        username: deploy
        privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
    

